const fs = require('fs');
const path = require('path');

const stylesPart1 = [
  // 1. Standard American Beer
  { id: '1A', code: '1A', name_zh: '美国清爽拉格', name_en: 'American Light Lager', category: '1', key: true, details: { tags: '标准强度, 拉格, 苍白色, 发泡型, 常见', overall_impression: '高碳酸杀口感，酒体非常轻盈，几乎没有风味，适合作为解渴的饮品。', aroma: '极低到没有麦芽香气，表现为轻微谷物、甜玉米味。酒花香气通常无。', appearance: '极浅的淡黄色到浅黄色。泡沫不可持久。清澈。', flavor: '清脆干爽。风味极低。略微玉米甜味。苦度极低。', mouthfeel: '酒体非常轻，水感。杀口感极强。沙口感。', stats: 'IBU: 8-12 | OG: 1.028-1.040 | FG: 0.998-1.008 | ABV: 2.8-4.2%' } },
  { id: '1B', code: '1B', name_zh: '标准美式拉格', name_en: 'American Lager', category: '1', key: true, details: { tags: '标准强度, 拉格, 苍白色, 发泡型', overall_impression: '一种极度清爽解渴的美国拉格，旨在最大程度迎合大众口味，清脆，极少风味。', aroma: '带有谷物或甜玉米香。基本没有酒花香。', appearance: '非常浅的淡黄色至中等黄色。清澈度高。', flavor: '比清爽拉格多一点点麦芽风味，干净干爽，玉米甜感。苦度低。', mouthfeel: '较轻的酒体，高碳酸杀口。', stats: 'IBU: 8-18 | OG: 1.040-1.050 | FG: 1.004-1.010 | ABV: 4.2-5.3%' } },
  { id: '1C', code: '1C', name_zh: '奶油爱尔', name_en: 'Cream Ale', category: '1', key: false, details: { tags: '标准强度, 爱尔, 苍白色', overall_impression: '一种干净、风味平衡、碳酸适中、发酵度高的美式基础啤酒。', aroma: '些许麦芽和玉米味，少许果酯。', appearance: '浅淡至金色。', flavor: '中低苦度，清脆顺滑。可能有淡淡玉米甜。', mouthfeel: '酒体中等偏轻。平滑，中至高碳酸。', stats: 'IBU: 8-20 | OG: 1.042-1.055 | FG: 1.006-1.012 | ABV: 4.2-5.6%' } },
  { id: '1D', code: '1D', name_zh: '美国小麦啤酒', name_en: 'American Wheat Beer', category: '1', key: false, details: { tags: '标准强度, 爱尔, 苍白色, 小麦', overall_impression: '一种清爽的小麦系啤酒，比德式小麦少了香蕉/丁香风味，更多展现中性发酵和美式酒花。', aroma: '面包/面团味小麦香。酒花香中等到低。', appearance: '浅黄到金色。通常有轻微雾度。', flavor: '轻柔的面包面团味，酒花风味中等。收口干爽。', mouthfeel: '中轻酒体。', stats: 'IBU: 15-30 | OG: 1.040-1.055 | FG: 1.008-1.013 | ABV: 4.0-5.5%' } },
  
  // 2. International Lager
  { id: '2A', code: '2A', name_zh: '国际淡色拉格', name_en: 'International Pale Lager', category: '2', key: true, details: { tags: '标准强度, 拉格, 苍白色', overall_impression: '清爽解渴，比美式拉格有更好的全麦芽感，或者苦度更高一些。大众市场的拉格。', aroma: '中低谷物感微甜麦芽香，少许花香/辛香酒花。', appearance: '淡黄色至金色。清澈。', flavor: '顺滑麦芽味，清脆，收口干爽。苦度稍高于美式。', mouthfeel: '中等偏轻酒体，较高碳酸。', stats: 'IBU: 18-25 | OG: 1.042-1.050 | FG: 1.008-1.012 | ABV: 4.5-6.0%' } },
  { id: '2B', code: '2B', name_zh: '国际琥珀拉格', name_en: 'International Amber Lager', category: '2', key: false, details: { tags: '标准强度, 拉格, 琥珀色', overall_impression: '易饮，有麦芽焦糖感但苦度极低，工业拉格的深色变种。', aroma: '一点烤面包、焦糖、谷物香。酒花存在感弱。', appearance: '琥珀到铜色。', flavor: '中低麦芽甜，带有焦糖吐司味。苦度低以支撑麦芽。', mouthfeel: '中轻到中等酒体。', stats: 'IBU: 8-25 | OG: 1.042-1.055 | FG: 1.008-1.014 | ABV: 4.5-6.0%' } },
  { id: '2C', code: '2C', name_zh: '国际深色拉格', name_en: 'International Dark Lager', category: '2', key: false, details: { tags: '标准强度, 拉格, 深色', overall_impression: '一种深色的工业拉格，有少许烤麦芽的颜色和风味，但不厚重。', aroma: '少许烤麦芽香如焦糖、轻微巧克力味。', appearance: '深琥珀到深棕色。清澈。', flavor: '甜麦芽味，少许烘培糖浆或太妃糖风味，收口稍干。', mouthfeel: '中轻酒体，易饮。', stats: 'IBU: 8-20 | OG: 1.044-1.056 | FG: 1.008-1.012 | ABV: 4.2-6.0%' } },

  // 3. Czech Lager
  { id: '3A', code: '3A', name_zh: '捷克淡色拉格', name_en: 'Czech Pale Lager', category: '3', key: false, details: { tags: '低强度, 拉格, 苍白色', overall_impression: '低酒精度版本的捷克拉格，日常饮品，清脆解渴且拥有不错的麦芽与酒花风味。', aroma: '萨兹酒花的辛香，加上烤面包状皮尔森麦芽香。', appearance: '非常浅淡黄色至金色。', flavor: '浓郁面包状麦芽甜，明显的酒花风味和中等苦度。尾韵干而持久。', mouthfeel: '中偏轻酒体。', stats: 'IBU: 20-35 | OG: 1.028-1.044 | FG: 1.008-1.014 | ABV: 3.0-4.1%' } },
  { id: '3B', code: '3B', name_zh: '捷克优质淡色拉格', name_en: 'Czech Premium Pale Lager', category: '3', key: true, details: { tags: '标准强度, 拉格, 苍白色', overall_impression: '众所周知的波西米亚皮尔森。麦芽饱满，酒花苦度明亮柔和，风味极致平衡且复杂。', aroma: '浓郁复杂的面包状全麦香，辛香花香的萨兹酒花香。双乙酰可被接受(微量)。', appearance: '金色。清澈到极清澈。浓厚的白色泡沫圈。', flavor: '非常饱满复杂的麦芽风味（微甜），伴随着突出的酒花柔和苦味。两者相互支撑。', mouthfeel: '中等酒体。中等碳酸。', stats: 'IBU: 30-45 | OG: 1.044-1.060 | FG: 1.013-1.017 | ABV: 4.2-5.8%' } },
  { id: '3C', code: '3C', name_zh: '捷克琥珀拉格', name_en: 'Czech Amber Lager', category: '3', key: false, details: { tags: '标准强度, 拉格, 琥珀色', overall_impression: '麦芽风味主导的拉格，带有焦糖/烤面包麦芽香并伴生萨兹香气，不像深色拉格那样深厚。', aroma: '强烈的焦糖和烤面包麦芽香气，适度的酒花气味。', appearance: '琥珀到铜色。', flavor: '复杂的麦芽味和焦糖甜味，但收尾依然保持拉格的干爽。', mouthfeel: '中偏饱满酒体。', stats: 'IBU: 20-35 | OG: 1.044-1.060 | FG: 1.013-1.017 | ABV: 4.4-5.8%' } },
  { id: '3D', code: '3D', name_zh: '捷克深色拉格', name_en: 'Czech Dark Lager', category: '3', key: false, details: { tags: '标准强度, 拉格, 深色', overall_impression: '丰富且深邃的麦芽驱动的拉格，同时伴有不同程度的烘培感和捷克酒花印记。', aroma: '丰富的面包麦芽，焦糖，可乐，少许巧克力及咖啡香。', appearance: '深红褐色到黑色。', flavor: '麦芽甜与可乐焦糖风味，少许烘焙咖啡味。酒花苦度适中但能被感知。', mouthfeel: '中偏饱满酒体，口感顺滑。', stats: 'IBU: 18-34 | OG: 1.044-1.060 | FG: 1.013-1.017 | ABV: 4.4-5.8%' } },

  // 4. Pale Malty European Lager
  { id: '4A', code: '4A', name_zh: '慕尼黑淡色拉格 (Helles)', name_en: 'Munich Helles', category: '4', key: true, details: { tags: '标准强度, 拉格, 苍白色, 德系', overall_impression: '麦芽前置且非常圆润干净的德国日常拉格，强调皮尔森麦芽的光滑面包风味。', aroma: '典型的谷物微甜麦芽香（面团/面包香）。酒花花香极淡。', appearance: '浅黄到金色。高度清澈，白色泡沫。', flavor: '略带甜感的谷物麦芽初味，苦度足够起到平衡但不抢戏，收口顺滑干净。', mouthfeel: '中等酒体。中等碳酸。完全不涩。', stats: 'IBU: 16-22 | OG: 1.044-1.048 | FG: 1.006-1.012 | ABV: 4.7-5.4%' } },
  { id: '4B', code: '4B', name_zh: '节日啤酒 (Festbier)', name_en: 'Festbier', category: '4', key: false, details: { tags: '标准强度, 拉格, 苍白色, 德系', overall_impression: '更烈、风味略显丰富的淡色拉格。慕尼黑啤酒节的专属标配，比三月啤酒颜色浅，麦芽感没那么烘烤。', aroma: '中等强度的鲜烤面包香，酒花香气属于支持位。', appearance: '略深的黄偏金色。', flavor: '坚实的带有轻微吐司感的麦芽甜，苦味干净，酒精度带来温润。', mouthfeel: '中等偏上酒体。', stats: 'IBU: 18-25 | OG: 1.054-1.057 | FG: 1.010-1.012 | ABV: 5.8-6.3%' } },
  { id: '4C', code: '4C', name_zh: '地狱啤酒 / 浅色博克', name_en: 'Helles Bock', category: '4', key: false, details: { tags: '烈性, 拉格, 苍白色, 德系', overall_impression: '强烈的麦芽型德国浅色拉格。风味饱满，有明显麦香与酒精度，但不具备深色博克的焦糖厚重感。', aroma: '浓郁深层谷物面包香气，可有少量草本花香酒花。', appearance: '深黄金到极轻微琥珀。', flavor: '饱满麦香，微微多士。由于高酒精度，带来微甜，收口平衡良好。', mouthfeel: '中偏上酒体，温暖。', stats: 'IBU: 23-35 | OG: 1.064-1.072 | FG: 1.011-1.018 | ABV: 6.3-7.4%' } },

  // 5. Pale Bitter European Beer
  { id: '5A', code: '5A', name_zh: '德国皮尔森', name_en: 'German Pils', category: '5', key: true, details: { tags: '标准强度, 拉格, 苍白色, 苦味, 德系', overall_impression: '极度清脆干净、苦度坚实且酒花突出的苍白德国拉格，高发酵度极度解渴。', aroma: '带有中等至强烈的辛香/花香德国贵族酒花味，干净的白面包皮尔森麦香。', appearance: '草黄色到浅金色，极其清澈，持久发泡白色酒头。', flavor: '干脆利落收尾，苦味持久鲜明。酒花风味中偏高。', mouthfeel: '较轻到中等轻盈，高碳酸杀口。', stats: 'IBU: 22-40 | OG: 1.044-1.050 | FG: 1.008-1.013 | ABV: 4.4-5.2%' } },
  { id: '5B', code: '5B', name_zh: '科隆啤酒 (Kölsch)', name_en: 'Kölsch', category: '5', key: true, details: { tags: '标准强度, 爱尔(低温发酵), 苍白色, 德系', overall_impression: '清爽细腻、带点果香和微弱酒花特征的干净艾尔，像拉格一样的发酵表现，科隆的骄傲。', aroma: '细致、有些花果香草味，伴随着淡淡蜂蜜或面包的皮尔森麦香。', appearance: '极度苍白。金黄、清澈无暇。', flavor: '柔和、微圆润的口感初段，随即转入干爽带着果香的花香微苦收尾。', mouthfeel: '轻至中等酒体。偏高碳酸。', stats: 'IBU: 18-30 | OG: 1.044-1.050 | FG: 1.007-1.011 | ABV: 4.4-5.2%' } },
  { id: '5C', code: '5C', name_zh: '德国出口拉格', name_en: 'German Helles Exportbier / Dortmunder', category: '5', key: false, details: { tags: '标准强度, 拉格, 苍白色, 德系', overall_impression: '比皮尔森麦香更重，比Helles更苦一些的水准平衡拉格。多特蒙德传统特色。', aroma: '平衡的面包麦芽味与贵族酒花辛香气。', appearance: '浅深黄到金色。清澈。', flavor: '酒花和麦芽风味并重，中等苦味，矿物感水质带来干爽清脆的收口。', mouthfeel: '中等略坚实的酒体。', stats: 'IBU: 20-30 | OG: 1.048-1.056 | FG: 1.010-1.015 | ABV: 4.8-6.0%' } },

  // 6. Amber Malty European Lager
  { id: '6A', code: '6A', name_zh: '三月啤酒 (Märzen)', name_en: 'Märzen', category: '6', key: true, details: { tags: '标准强度, 拉格, 琥珀色, 德系', overall_impression: '经典的慕尼黑烤麦芽节气啤酒，拥有浓郁烘烤吐司味，但不苦且无焦糖味。', aroma: '浓郁的德式烤面包如脆皮面包、饼干。无烘烤焦糊味或焦糖。', appearance: '较深的琥珀到铜红色。亮泽清澈。', flavor: '初入口是饱满绵密的面包麦芽甜味，然后是收敛的干爽。完美的拉格干净底子。', mouthfeel: '中等酒体有着圆润质感。', stats: 'IBU: 18-24 | OG: 1.054-1.060 | FG: 1.010-1.014 | ABV: 5.8-6.3%' } },
  { id: '6B', code: '6B', name_zh: '烟熏啤酒 (Rauchbier)', name_en: 'Rauchbier', category: '6', key: false, details: { tags: '标准强度, 拉格, 琥珀色, 德系', overall_impression: '以班贝格当地山毛榉木熏制的麦芽制作的类似三月啤酒/慕尼黑深色基础的深色拉格，烟熏火腿气息浓郁。', aroma: '优雅而明确的木头烟熏、培根、火腿味，衬托于绵密的烤麦芽香之上。', appearance: '暗琥珀到深红棕色。', flavor: '烟熏味道如同柴火般醇厚，搭配有焦糊、面包皮质感的浓郁麦香，极强辨识度。', mouthfeel: '中等饱满。', stats: 'IBU: 20-30 | OG: 1.050-1.057 | FG: 1.012-1.016 | ABV: 4.8-6.0%' } },
  { id: '6C', code: '6C', name_zh: '维也纳拉格', name_en: 'Vienna Lager', category: '6', key: true, details: { tags: '标准强度, 拉格, 琥珀色, 奥系', overall_impression: '一款带有优雅麦酒风味、略呈红铜色、均衡爽口的欧洲拉格，烤面包香十足但不甜腻。', aroma: '中偏强维也纳麦芽的烤面包味。微微的花卉酒花。', appearance: '琥珀带铜红色调。清亮。', flavor: '显著但柔和的烘焙麦芽特征，适度苦度，收口依然保留拉格的干脆爽性，不厚重。', mouthfeel: '偏轻到中等酒体。', stats: 'IBU: 18-30 | OG: 1.046-1.052 | FG: 1.010-1.014 | ABV: 4.7-5.5%' } },

  // 7. Amber Bitter European Beer
  { id: '7B', code: '7B', name_zh: '老啤酒 (Altbier)', name_en: 'Altbier', category: '7', key: true, details: { tags: '标准强度, 爱尔(低温发酵), 琥珀色, 德系', overall_impression: '杜塞尔多夫的骄傲：一种极其干净、高苦度度、麦香深邃浓郁的铜色艾尔。', aroma: '干净的麦芽香带一点果酥香，贵族酒花的辛辣、草本或花香非常和谐。', appearance: '从亮红到深铜色。透亮。', flavor: '前期是坚实显著的高麦芽味夹带一点烤坚果味，而后迅速转为干爽极具冲击力的高酒花苦味收口。', mouthfeel: '中等酒体，光滑微干。', stats: 'IBU: 25-50 | OG: 1.044-1.052 | FG: 1.008-1.014 | ABV: 4.3-5.5%' } },

  // 8. Dark European Lager
  { id: '8A', code: '8A', name_zh: '慕尼黑深色拉格', name_en: 'Munich Dunkel', category: '8', key: true, details: { tags: '标准强度, 拉格, 深色, 德系', overall_impression: '展现了慕尼黑麦芽（深入烘焙但不焦糊）独特风尚的深褐色拉格，液体面包的本尊。', aroma: '极其丰富深邃的面包心、吐司边、少许巧克力和焦糖香气，但并非烘烤的糊味。', appearance: '深红褐色到棕/黑色。带点红色折光。', flavor: '满口的巧克力面包、太妃糖、饼干风味包围，苦度低因此感觉麦香甜美复杂，但由于底层是拉格，依然顺滑易饮。', mouthfeel: '中等至饱满酒体，不涩。', stats: 'IBU: 18-28 | OG: 1.048-1.056 | FG: 1.010-1.016 | ABV: 4.5-5.6%' } },
  { id: '8B', code: '8B', name_zh: '黑拉格 (Schwarzbier)', name_en: 'Schwarzbier', category: '8', key: true, details: { tags: '标准强度, 拉格, 深色, 德系', overall_impression: '比慕尼黑Dunkel麦香少点、烤味多但无美式世涛般焦苦味的一种深黑而干爽的拉格。', aroma: '轻微至中等程度被烘焙的深色麦芽香，少许黑巧克力味。无果香。', appearance: '几乎全黑，深宝石红底色。', flavor: '伴随着干脆拉格底子的一层冷烘焙咖啡、轻度黑巧风味，完全无涩味，非常非常干净利落。', mouthfeel: '中轻酒体，丝滑微碳酸。', stats: 'IBU: 20-30 | OG: 1.046-1.052 | FG: 1.010-1.016 | ABV: 4.4-5.4%' } },

  // 9. Strong European Beer
  { id: '9A', code: '9A', name_zh: '双倍博克 (Doppelbock)', name_en: 'Doppelbock', category: '9', key: true, details: { tags: '烈性, 拉格, 深色, 德系', overall_impression: '非常醇厚、浓烈、麦香极高而苦味低沉的修道士液体面包圣物。', aroma: '非常沉重的富含面包含糖成分的深色麦香。黑葡萄干、李子干等美拉德反应带来的深色干果香。', appearance: '深古铜色至深棕色。有深红高光。', flavor: '麦芽风味像巨大的棉被一样包裹舌头，显著但顺滑的美拉德反应焦香甜味。高酒精度带来微甜感，几乎无酒花。', mouthfeel: '酒体极其饱满，顺滑度极高，具有温润感。', stats: 'IBU: 16-26 | OG: 1.072-1.112 | FG: 1.016-1.024 | ABV: 7.0-10.0%' } },
  { id: '9B', code: '9B', name_zh: '冰博克 (Eisbock)', name_en: 'Eisbock', category: '9', key: false, details: { tags: '强冰馏, 拉格, 深色, 德系', overall_impression: '德国博克的终极增强版，通过冷冻结冰并去除水分提纯精华。极其浓缩。', aroma: '极致复杂的液化果脯、葡萄干、太妃糖、黑加仑香气，伴随明显醇香。', appearance: '深古铜到暗褐色。往往像糖浆一样浑厚。', flavor: '如同强效深色麦芽糖浆原液，风味极为丰沛有如波特酒（Port Wine）。醇厚饱满几乎可咀嚼。', mouthfeel: '糖浆般的浑厚饱满，热烈灼烧感。', stats: 'IBU: 25-35 | OG: 1.078-1.120 | FG: 1.020-1.035 | ABV: 9.0-14.0%' } },
  { id: '9C', code: '9C', name_zh: '波罗的海波特', name_en: 'Baltic Porter', category: '9', key: true, details: { tags: '烈性, 拉格(往往), 深色, 波罗的海', overall_impression: '起源于英国波特但在波罗的海地区经过高纬度改良为拉格发酵体系，产生类似烈性深色博克但带有波特焦糊味的独特重型黑啤。', aroma: '复杂的深麦香，巧克力、太妃、坚果味伴有樱桃或乌梅的果酯。', appearance: '深不透明褐色到深黑色。', flavor: '融合了帝王世涛般的柔和烘焙与黑色果实风味，通过拉格酵母实现干净且带有些许咖啡焦糖顺滑质感。', mouthfeel: '醇厚饱满，碳酸感中至上。', stats: 'IBU: 20-40 | OG: 1.060-1.090 | FG: 1.016-1.024 | ABV: 6.5-9.5%' } },

  // 10. German Wheat Beer
  { id: '10A', code: '10A', name_zh: '德国小麦啤酒 (Weissbier)', name_en: 'Weissbier', category: '10', key: true, details: { tags: '标准强度, 爱尔(小麦), 苍白色, 德系', overall_impression: '极为经典、令人垂涎的巴伐利亚淡色小麦，依靠特有的酵母带来明显香蕉与丁香风味。', aroma: '强烈的熟香蕉或泡泡糖气味，并交织着鲜明的丁香（辛香/酚类）味。可带有一丝香草味。', appearance: '因为富含蛋白和酵母所以非常浑浊（云雾缭绕）。苍白至金色，巨大的慕斯般白色酒头。', flavor: '香蕉和丁香的特征主导，小麦特有的面包面团味穿插其中，几乎没有酒花苦味。', mouthfeel: '丰满且软绵的面包嚼感，同时伴有极其强烈的杀口感。', stats: 'IBU: 8-15 | OG: 1.044-1.052 | FG: 1.010-1.014 | ABV: 4.3-5.6%' } },
  { id: '10B', code: '10B', name_zh: '深色小麦啤酒', name_en: 'Dunkles Weissbier', category: '10', key: false, details: { tags: '标准强度, 爱尔(小麦), 深色, 德系', overall_impression: '类似于小麦啤酒基础但结合了一定程度的慕尼黑深色麦芽带来的太妃/巧克力味。', aroma: '香蕉/丁香味依然存在，但深红色焦糖和小麦深度的丰富面包皮香交织。', appearance: '浅红木到深太妃糖褐色。云雾浑浊。', flavor: '丁香香蕉基础风味配上了丰富的麦芽焦糖、烤吐司感。低酒花苦。', mouthfeel: '饱满、慕斯般的口感，高碳酸。', stats: 'IBU: 10-18 | OG: 1.044-1.056 | FG: 1.010-1.014 | ABV: 4.3-5.6%' } },
  { id: '10C', code: '10C', name_zh: '小麦博克', name_en: 'Weizenbock', category: '10', key: true, details: { tags: '烈性, 爱尔(小麦), 苍白或深色, 德系', overall_impression: '麦香强烈的德国高酒精度小麦啤酒，将巴伐利亚小麦酵母的香气与类似博克般的厚重质感融为一体。', aroma: '香蕉/丁香味极为浓缩扑鼻，混合着布李子、乌梅黑果脂香。', appearance: '可能是金色（较罕见）或深棕色，浑浊，巨大酒帽。', flavor: '丰饶的浓醇果酯和深色焦香面包、黑香蕉糕的重度结合，复杂微甜。高醇厚度支撑。', mouthfeel: '如丝绸般厚重，同时拥有高碳酸感。有酒精温润感。', stats: 'IBU: 15-30 | OG: 1.064-1.090 | FG: 1.015-1.022 | ABV: 6.5-9.0%' } },
];

fs.writeFileSync(
  path.join(__dirname, 'generate_bjcp_part1.json'),
  JSON.stringify(stylesPart1, null, 2)
);

console.log('Part 1 saved.');
